---
# Stage 1: install OS packages and dependencies from PyPI
version: 3

dependencies:
  system:
    - git [platform:rpm]
    - jq [platform:rpm]
    - sudo [platform:rpm]
    - python3-cryptography [platform:rpm]
    - python3-jmespath [platform:rpm]
    - python3-lxml [platform:rpm]
    - python3-six [platform:rpm]
    - python3-setuptools [platform:rpm]
    - python3-requests [platform:rpm]
  ansible_core:
    package_pip: ansible-core==ANSIBLE_VERSION
  ansible_runner:
    package_pip: ansible-runner
  python:
    - ara[client]
    - ansible_merge_vars
    - dnspython
    - netaddr
    - passlib
    - pyvmomi
    - pyOpenSSL
    - pytz
    - python-dateutil

options:
  package_manager_path: /usr/bin/dnf

images:
  base_image:
    name: docker.io/redhat/ubi9:latest
